import React, { useState } from 'react';
import {
  Sparkles,
  Search,
  Filter,
  CheckCircle2,
  X,
  Building2,
  DollarSign,
  Clock,
  Layers,
  ArrowRight,
  TrendingUp,
  Sliders,
  ShieldCheck,
  Zap,
  HelpCircle,
  Eye
} from 'lucide-react';
import { useAi } from './AiContext';
import { AiOptimizationSuggestion } from './data/mockAiData';
import { cn } from '../../../../lib/utils';

export function AiOptimizationPage() {
  const {
    projects,
    selectedProjectId,
    setSelectedProjectId,
    selectedProject,
    optimizations,
    applyOptimization,
    dismissOptimization,
    portfolioRollup
  } = useAi();

  const [categoryFilter, setCategoryFilter] = useState('All');
  const [engineFilter, setEngineFilter] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedOptForModal, setSelectedOptForModal] = useState<AiOptimizationSuggestion | null>(null);

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(val);
  };

  const filteredOptimizations = optimizations.filter((opt) => {
    const matchesCategory = categoryFilter === 'All' || opt.category === categoryFilter;
    const matchesEngine = engineFilter === 'All' || opt.engine === engineFilter;
    const matchesSearch =
      opt.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      opt.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      opt.projectName.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesProject =
      selectedProjectId === 'all' ||
      opt.projectId === 'all' ||
      opt.projectId === selectedProjectId;

    return matchesCategory && matchesEngine && matchesSearch && matchesProject;
  });

  const pendingOptimizations = filteredOptimizations.filter((o) => o.status !== 'Dismissed');

  return (
    <div className="w-full h-full flex flex-col gap-6 animate-in fade-in duration-300 overflow-y-auto pr-1 text-left">
      {/* Top Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-md bg-[#A0D6B422] text-slate-800 dark:text-[#A0D6B4] border border-[#A0D6B444] text-xs font-black uppercase tracking-wider">
              Continuous Optimization Engine
            </span>
            <span className="text-xs text-slate-400 font-semibold">• Cognitive Margin & Schedule Protection</span>
          </div>
          <h1 className="text-2xl lg:text-3xl font-black text-slate-900 dark:text-white mt-1 tracking-tight">
            AI Optimization Suggestions & Value Engineering
          </h1>
          <p className="text-xs sm:text-sm font-medium text-slate-500 dark:text-slate-400 mt-0.5">
            Systemic recommendations generated by continuous monitoring of Studio finish specs, Cost PO rates, Flow dependencies, and People utilization.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {/* Project Scope Filter */}
          <div className="flex items-center gap-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-1.5 rounded-xl text-xs shadow-sm">
            <Building2 className="w-3.5 h-3.5 text-[#A0D6B4]" />
            <select
              value={selectedProjectId}
              onChange={(e) => setSelectedProjectId(e.target.value)}
              className="text-xs font-bold text-slate-800 dark:text-slate-100 bg-transparent border-none outline-none cursor-pointer"
            >
              <option value="all">Portfolio Scope (All Projects — {projects.length} Active Project{projects.length === 1 ? '' : 's'})</option>
              {projects.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.code} — {p.name}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Value Realization Banner */}
      <div className="p-6 rounded-xl bg-slate-900 text-white shadow-sm flex flex-col md:flex-row items-center justify-between gap-6 border border-slate-800">
        <div className="space-y-1 max-w-xl">
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-[#A0D6B433] text-[#A0D6B4]">
              Identified Optimization Pool
            </span>
            <span className="text-xs text-slate-400 font-semibold">• Ready for 1-Click Execution</span>
          </div>
          <h3 className="text-2xl font-black text-white">
            {formatCurrency(portfolioRollup.totalValueEngineeringINR)} Total Identified Savings
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            Applying all pending value engineering and critical path parallelizations will recover up to <strong>+{portfolioRollup.preventedDelayDays} calendar days</strong> across active site deliveries.
          </p>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <div className="p-3.5 rounded-xl bg-slate-800/90 border border-slate-700 text-center">
            <span className="text-[10px] text-slate-400 font-bold block uppercase">Pending Suggestions</span>
            <span className="text-xl font-black text-white block mt-0.5">
              {optimizations.filter((o) => o.status === 'Pending Review').length}
            </span>
          </div>
          <div className="p-3.5 rounded-xl bg-slate-800/90 border border-slate-700 text-center">
            <span className="text-[10px] text-slate-400 font-bold block uppercase">Applied Realized</span>
            <span className="text-xl font-black text-emerald-400 block mt-0.5">
              {optimizations.filter((o) => o.status === 'Applied').length}
            </span>
          </div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-3 bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search suggestions, materials, savings..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-1.5 text-xs bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg outline-none focus:ring-2 focus:ring-[#A0D6B4] text-slate-900 dark:text-white"
          />
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Category Filter */}
          <div className="flex items-center gap-1.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 px-2.5 py-1 rounded-lg text-xs">
            <span className="text-slate-400 font-semibold">Category:</span>
            <select
              value={categoryFilter}
              onChange={(e) => setCategoryFilter(e.target.value)}
              className="bg-transparent font-bold text-slate-800 dark:text-slate-200 outline-none cursor-pointer"
            >
              <option value="All">All Categories</option>
              <option value="Value Engineering">Value Engineering</option>
              <option value="Schedule Compression">Schedule Compression</option>
              <option value="Procurement Synergy">Procurement Synergy</option>
              <option value="Resource Rebalancing">Resource Rebalancing</option>
            </select>
          </div>

          {/* Engine Filter */}
          <div className="flex items-center gap-1.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 px-2.5 py-1 rounded-lg text-xs">
            <span className="text-slate-400 font-semibold">Engine:</span>
            <select
              value={engineFilter}
              onChange={(e) => setEngineFilter(e.target.value)}
              className="bg-transparent font-bold text-slate-800 dark:text-slate-200 outline-none cursor-pointer"
            >
              <option value="All">All Engines</option>
              <option value="Studio">Studio</option>
              <option value="Cost">Cost</option>
              <option value="Flow">Flow</option>
              <option value="Quest">Quest</option>
              <option value="Vendor">Vendor</option>
              <option value="People">People</option>
              <option value="Connect">Connect</option>
            </select>
          </div>
        </div>
      </div>

      {/* Optimizations List */}
      <div className="space-y-4">
        {pendingOptimizations.map((opt) => (
          <div
            key={opt.id}
            className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm hover:border-[#A0D6B4]/60 transition-all flex flex-col lg:flex-row lg:items-center justify-between gap-4"
          >
            {/* Left Details */}
            <div className="space-y-2 max-w-2xl">
              <div className="flex flex-wrap items-center gap-2">
                <span
                  className={cn(
                    'text-[10px] font-black uppercase px-2 py-0.5 rounded',
                    opt.priority === 'Urgent' && 'bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300',
                    opt.priority === 'High' && 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300',
                    opt.priority === 'Medium' && 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300'
                  )}
                >
                  {opt.priority} Priority
                </span>
                <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">
                  {opt.engine} Engine
                </span>
                <span className="text-[11px] font-bold text-slate-400">
                  Project: <strong className="text-slate-700 dark:text-slate-200">{opt.projectName}</strong>
                </span>
              </div>

              <h3 className="font-extrabold text-slate-900 dark:text-white text-base">
                {opt.title}
              </h3>

              <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                {opt.description}
              </p>

              <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60 text-[11px] font-medium text-slate-700 dark:text-slate-300">
                <strong className="text-emerald-700 dark:text-[#A0D6B4] block text-[10px] uppercase font-black mb-0.5">
                  Systemic Action Outcome:
                </strong>
                {opt.actionSummary}
              </div>
            </div>

            {/* Right Financial/Timeline Impacts & Actions */}
            <div className="flex flex-wrap items-center gap-4 lg:self-center border-t lg:border-t-0 pt-3 lg:pt-0 border-slate-100 dark:border-slate-800">
              <div className="text-right text-xs space-y-1 pr-2">
                {opt.impactSavingINR > 0 && (
                  <div>
                    <span className="text-slate-400 text-[10px] font-bold block uppercase">Cost Saving</span>
                    <strong className="text-base font-black text-emerald-600 dark:text-[#A0D6B4]">
                      {formatCurrency(opt.impactSavingINR)}
                    </strong>
                  </div>
                )}
                {opt.impactTimeDays > 0 && (
                  <div>
                    <span className="text-slate-400 text-[10px] font-bold block uppercase">Schedule Float</span>
                    <strong className="text-sm font-black text-purple-600 dark:text-purple-400">
                      +{opt.impactTimeDays} Days
                    </strong>
                  </div>
                )}
                <span className="text-[10px] text-slate-400 font-semibold block">
                  Confidence: {opt.confidenceScore}%
                </span>
              </div>

              {opt.status === 'Applied' ? (
                <div className="px-4 py-2 rounded-lg bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-[#A0D6B4] font-black text-xs flex items-center gap-1.5 shadow-sm">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Applied to Core</span>
                </div>
              ) : (
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => dismissOptimization(opt.id)}
                    className="p-2 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-400 hover:text-slate-600 dark:hover:text-white transition-all"
                    title="Dismiss Suggestion"
                  >
                    <X className="w-4 h-4" />
                  </button>

                  <button
                    onClick={() => applyOptimization(opt.id)}
                    className="px-4 py-2 rounded-lg bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-black text-xs shadow-sm hover:opacity-90 transition-all flex items-center gap-1.5"
                  >
                    <Sparkles className="w-3.5 h-3.5 text-[#A0D6B4]" />
                    <span>Apply Optimization</span>
                  </button>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
