export type NestPlanId = 'nest_starter' | 'nest_plus' | 'nest_pro';

export type GroupCategory = 'Family' | 'Roommates' | 'Trip & Vacation' | 'Friends Circle' | 'Project Group';

export type MemberRole = 'Admin' | 'Member' | 'Viewer';

export type RecurringFrequency = 'weekly' | 'bi-weekly' | 'monthly' | 'quarterly' | 'yearly';

export interface NestMember {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: MemberRole;
  joinedDate: string;
  phone?: string;
  contributionPercent?: number;
  monthlyAllowance?: number;
  allowanceDisbursedThisMonth?: number;
  allowanceScheduleDay?: number; // e.g. 1st of each month
  isCurrentUser?: boolean;
}

export type ExpenseCategory =
  | 'Groceries'
  | 'Rent & Utilities'
  | 'Dining & Food'
  | 'Transport'
  | 'Entertainment'
  | 'Healthcare'
  | 'Vacation & Travel'
  | 'Education'
  | 'Shopping'
  | 'Shared Vaults'
  | 'Income & Allowance';

export interface NestRecurringRule {
  id: string;
  title: string;
  amount: number;
  type: 'expense' | 'income' | 'savings_goal' | 'vault_transfer' | 'allowance';
  category: ExpenseCategory;
  frequency: RecurringFrequency;
  dayOfMonth: number; // 1 to 31
  nextDueDate: string;
  paidByMemberId: string;
  paidByMemberName: string;
  targetId?: string; // goalId, vaultId, or memberId (for allowance)
  targetName?: string;
  splitWithMemberIds?: string[];
  splitType?: 'equal' | 'exact' | 'percentage';
  isActive: boolean;
  autoProcess: boolean;
  lastExecutedDate?: string;
  notes?: string;
}

export interface NestTransaction {
  id: string;
  title: string;
  amount: number; // Positive for income, negative for expense
  type: 'expense' | 'income' | 'transfer';
  category: ExpenseCategory;
  date: string;
  paidByMemberId: string;
  paidByMemberName: string;
  splitWithMemberIds: string[];
  splitType: 'equal' | 'exact' | 'percentage';
  splitBreakdown?: { memberId: string; amount: number }[];
  receiptUrl?: string;
  notes?: string;
  status: 'settled' | 'pending';
  vaultId?: string;
  recurringRuleId?: string;
  isRecurringGenerated?: boolean;
}

export interface NestBudget {
  id: string;
  category: ExpenseCategory;
  monthlyLimit: number;
  currentSpent: number;
  color: string;
  iconName: string;
  alertThreshold: number; // e.g., 85%
}

export interface NestSavingsGoal {
  id: string;
  title: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string;
  category: string;
  imageUrl?: string;
  color: string;
  monthlyAutoDeposit?: number;
  autoDepositActive?: boolean;
  autoDepositScheduleDay?: number;
  recurringActive?: boolean;
  contributors: { memberId: string; amount: number }[];
}

export interface NestVault {
  id: string;
  name: string;
  balance: number;
  purpose: string;
  color: string;
  targetBalance?: number;
  monthlyAutoDeposit?: number;
  autoDepositActive?: boolean;
  autoDepositScheduleDay?: number;
  monthlyAutoAllocation?: number;
  recurringActive?: boolean;
  members: string[];
}

export interface NestGroup {
  id: string;
  name: string;
  type: GroupCategory;
  avatar: string;
  plan: NestPlanId;
  totalMembersCount: number;
  currency: string;
  createdAt: string;
  monthlyIncome: number;
  monthlyBudget: number;
  currentMonthSpend: number;
}

export type NestReminderType = 
  | 'expense_bill' 
  | 'income_due' 
  | 'savings_deposit' 
  | 'vault_allocation' 
  | 'allowance_disbursement' 
  | 'budget_alert' 
  | 'custom_task';

export type NestReminderStatus = 'pending' | 'completed' | 'snoozed' | 'dismissed';

export type NestReminderPriority = 'urgent' | 'high' | 'medium' | 'low';

export interface NestReminderItem {
  id: string;
  title: string;
  description?: string;
  amount?: number;
  type: NestReminderType;
  category?: ExpenseCategory;
  dueDate: string; // YYYY-MM-DD
  status: NestReminderStatus;
  priority: NestReminderPriority;
  assignedMemberId?: string;
  assignedMemberName?: string;
  relatedRuleId?: string;
  relatedGoalId?: string;
  relatedVaultId?: string;
  relatedBudgetId?: string;
  isAutoGenerated?: boolean;
  completedAt?: string;
  tags?: string[];
  recurringFrequency?: RecurringFrequency;
}

